name: simple_ci

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "24.x"

      - name: print lint
        run: echo "lint started"

      - name: lint check
        run: npm run lint

      - name: finish lint
        run: echo "link finished"

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "24.x"

      - name: print test
        run: echo "test started"

      - name: test check
        run: npm test

      - name: install modules
        run: npm install

      - name: finish lint
        run: echo "test finished"

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "24.x"

      - name: print deploy
        run: echo "test started"

      - name: install modules
        run: npm install

      - name: test deploy
        run: npm run deploy

      - name: finish deploy
        run: echo "deploy finished"
